events {}

http {
  resolver 127.0.0.11 valid=10s;

  server {
    listen 80;

    location /usuarios/ {
      set $usuarios_backend http://usuarios:80;
      rewrite ^/usuarios/(.*)$ /$1 break;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass $usuarios_backend;
    }

    location /productos/ {
      set $productos_backend http://productos:80;
      rewrite ^/productos/(.*)$ /$1 break;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass $productos_backend;
    }

    location / {
      set $shell_backend http://shell:80;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass $shell_backend;
    }
  }
}
